treewide: improve bash error reporting
bash error handling and reporting is atrocious. Without -e it will
just ignore errors. With -e it will stop on errors, but not report
where the error happened (apart from exiting itself with an error code).

Improve that with the `trap ERR` command. Note that this won't be invoked
on intentional error exit with `exit 1`.

We apply this on every bash script that contains -e or that it appears
trivial to set it in. Non-trivial scripts without -e are left unmodified,
since they might intentionally invoke failing scripts.

Closes scylladb/scylladb#22747

diff --git a/bin/cqlsh b/bin/cqlsh
--- a/bin/cqlsh
+++ b/bin/cqlsh
@@ -1,7 +1,9 @@
-#!/bin/bash
+#!/bin/bash -e
 
 # Copyright (C) 2023-present ScyllaDB
 # SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0
+
+trap 'echo "error $? in $0 line $LINENO"' ERR
 
 here=$(dirname "$0")
 exec "$here/../tools/cqlsh/bin/cqlsh.py" "$@"
diff --git a/bin/nodetool b/bin/nodetool
--- a/bin/nodetool
+++ b/bin/nodetool
@@ -1,10 +1,12 @@
-#!/bin/bash
+#!/bin/bash -e
 #
 # Copyright (C) 2024-present ScyllaDB
 #
 #
 # SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0
 #
+
+trap 'echo "error $? in $0 line $LINENO"' ERR
 
 SCRIPT_PATH=$(dirname $(realpath "$0"))
 
