dist/common/scripts: prevent misinterpret blank input as '/dev/', show error when inputted device path is not found
Fixes #1110

Signed-off-by: Takuya ASADA <syuu@scylladb.com>
Message-Id: <1459267786-19123-1-git-send-email-syuu@scylladb.com>

diff --git a/dist/common/scripts/scylla_raid_setup b/dist/common/scripts/scylla_raid_setup
--- a/dist/common/scripts/scylla_raid_setup
+++ b/dist/common/scripts/scylla_raid_setup
@@ -37,6 +37,13 @@ if [ "$DISKS" = "" ]; then
     print_usage
 fi
 
+for dsk in $DISKS; do
+    if [ ! -b $dsk ]; then
+        echo "$dsk is not found"
+        exit 1
+    fi
+done
+
 echo Creating RAID0 for scylla using $NR_DISK disk\(s\): $DISKS
 if [ -e $RAID ]; then
     echo "$RAID is already using"
