dist: interactive scylla_setup
Signed-off-by: Takuya ASADA <syuu@scylladb.com>

diff --git a/dist/common/scripts/scylla_setup b/dist/common/scripts/scylla_setup
--- a/dist/common/scripts/scylla_setup
+++ b/dist/common/scripts/scylla_setup
@@ -23,6 +23,22 @@ print_usage() {
     exit 1
 }
 
+interactive_ask_service() {
+    echo $1
+    while true; do
+        echo -n "yes/no: "
+        read ans
+        case $ans in
+            "y" | "yes")
+                return 1
+                ;;
+            "n" | "no")
+                return 0
+                ;;
+        esac
+    done
+}
+
 AMI=0
 ENABLE_SERVICE=1
 SELINUX_SETUP=1
@@ -31,6 +47,12 @@ NTP_SETUP=1
 RAID_SETUP=1
 COREDUMP_SETUP=1
 SYSCONFIG_SETUP=1
+
+if [ $# -ne 0 ]; then
+    INTERACTIVE=0
+else
+    INTERACTIVE=1
+fi
 
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -85,15 +107,19 @@ while [ $# -gt 0 ]; do
     esac
 done
 
-if [ $RAID_SETUP -eq 1 ] && [ "$DISKS" = "" ]; then
+if [ $INTERACTIVE -eq 0 ] && [ $RAID_SETUP -eq 1 ] && [ "$DISKS" = "" ]; then
     print_usage
 fi
-if [ $SYSCONFIG_SETUP -eq 1 ] && [ "$NIC" = "" ]; then
+if [ $INTERACTIVE -eq 0 ] && [ $SYSCONFIG_SETUP -eq 1 ] && [ "$NIC" = "" ]; then
     print_usage
 fi
 
 . /etc/os-release
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to enable ScyllaDB services?" &&:
+    ENABLE_SERVICE=$?
+fi
 if [ $ENABLE_SERVICE -eq 1 ]; then
     if [ "$ID" = "fedora" ] || [ "$ID" = "centos" ]; then
         systemctl enable scylla-server.service
@@ -101,14 +127,26 @@ if [ $ENABLE_SERVICE -eq 1 ]; then
     fi
 fi
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to disable SELinux?" &&:
+    SELINUX_SETUP=$?
+fi
 if [ $SELINUX_SETUP -eq 1 ]; then
     /usr/lib/scylla/scylla_selinux_setup
 fi
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to setup bootloader options?" &&:
+    BOOTPARAM_SETUP=$?
+fi
 if [ $BOOTPARAM_SETUP -eq 1 ]; then
     /usr/lib/scylla/scylla_bootparam_setup
 fi
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to setup NTP?" &&:
+    NTP_SETUP=$?
+fi
 if [ $NTP_SETUP -eq 1 ]; then
     if [ "$NTP_DOMAIN" != "" ]; then
         /usr/lib/scylla/scylla_ntp_setup --subdomain $NTP_DOMAIN
@@ -117,10 +155,39 @@ if [ $NTP_SETUP -eq 1 ]; then
     fi
 fi
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to setup RAID?" &&:
+    RAID_SETUP=$?
+    if [ $RAID_SETUP -eq 1 ]; then
+        echo "Please select disks from following list: "
+        while true; do
+            lsblk -d -i -n -p -r|awk '{print $1}'|sed -e ':loop;N;$!b loop;s/\n/ /g'
+            echo "type 'done' to finish selection. selected: $DISKS"
+            echo -n "> "
+            read dsk
+            if [ "$dsk" = "done" ]; then
+                break
+            fi
+            if [ -e $dsk ]; then
+                if [ "$DISKS" = "" ]; then
+                    DISKS=$dsk
+                else
+                    DISKS="$DISKS,$dsk"
+                fi
+            else
+                echo "$dsk not found"
+            fi
+        done
+    fi
+fi
 if [ $RAID_SETUP -eq 1 ]; then
     /usr/lib/scylla/scylla_raid_setup --disks $DISKS --update-fstab
 fi
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to setup coredump?" &&:
+    COREDUMP_SETUP=$?
+fi
 if [ $COREDUMP_SETUP -eq 1 ]; then
     if [ "$DISKS" != "" ]; then
         /usr/lib/scylla/scylla_coredump_setup --dump-to-raiddir
@@ -129,6 +196,21 @@ if [ $COREDUMP_SETUP -eq 1 ]; then
     fi
 fi
 
+if [ $INTERACTIVE -eq 1 ]; then
+    interactive_ask_service "Do you want to setup sysconfig?" &&:
+    SYSCONFIG_SETUP=$?
+    if [ $SYSCONFIG_SETUP -eq 1 ]; then
+        echo "Please select NIC from following list: "
+        while true; do
+            ls /sys/class/net
+            echo -n "> "
+            read NIC
+            if [ -e /sys/class/net/$NIC ]; then
+                break
+            fi
+        done
+    fi
+fi
 if [ $SYSCONFIG_SETUP -eq 1 ]; then
     /usr/lib/scylla/scylla_sysconfig_setup --nic $NIC
 fi
