treewide: improve bash error reporting
bash error handling and reporting is atrocious. Without -e it will
just ignore errors. With -e it will stop on errors, but not report
where the error happened (apart from exiting itself with an error code).

Improve that with the `trap ERR` command. Note that this won't be invoked
on intentional error exit with `exit 1`.

We apply this on every bash script that contains -e or that it appears
trivial to set it in. Non-trivial scripts without -e are left unmodified,
since they might intentionally invoke failing scripts.

diff --git a/tools/toolchain/prepare b/tools/toolchain/prepare
--- a/tools/toolchain/prepare
+++ b/tools/toolchain/prepare
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+trap 'echo "error $? in $0 line $LINENO"' ERR
+
 if ! command -v buildah > /dev/null; then
     echo install buildah 1.19.3 or later
     exit 1
